[workspace]
resolver = "3"
members = [
    "crates/app_kit",
    "crates/core_foundation",
    "crates/ffi_utils",
    "crates/objc",
]

[workspace.package]
version = "0.0.0"
authors = ["Tianjiao Nie"]
edition = "2024"

[workspace.dependencies]
ffi_utils = { path = "crates/ffi_utils" }
